Lookup Agent Pool ID By Name
hashicorp/terraform-k8s pull request #93
Opened 2021-03-24 21:28 UTC by tsunamishaun

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #63

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-k8s/blob/master/CHANGELOG.md):

```release-note
* Adds AgentPoolName to Workspace CRD & Automatic lookup of AgentPoolID from AgentPoolName
```
note to maintainers/reviewers:

I've opened in draft mode in case there are glaring issues with these changes, if/when you think its ready for a formal PR please let me know!

This came out of the need for the ability to lookup agent pools based on name (or eventually something like filter/query). After looking at the code I was reminded that features around agent pool are new and first pass it would be nice to get the name feedable through the helm chart, then address maybe how to better structure agentpool id/name/(query?).  It might also make sense to add the workspace helper for agent pool, I just ran out of time but would be a good thing to have for future feature work (thoughts?).

2021-03-24 21:28 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-k8s?pullRequest=93)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-k8s?pullRequest=93)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-k8s?pullRequest=93).</sub>

2021-06-29 17:50 UTC, tsunamishaun commented
Hi @koikonom! I was wondering if you had any cycles for a review? I don't believe I have enough permission to request but would absolutely appreciate some feedback.

2021-07-01 10:47 UTC, koikonom requested changes
Hello @tsunamishaun !

This looks good, thanks for the effort. Would you mind rebasing your branch on top of the latest master branch before we merge this?

Thanks!

2021-07-06 15:46 UTC, tsunamishaun commented
@koikonom I just rebased, thanks for your review!!

2021-07-08 12:04 UTC, koikonom approved these changes

2021-07-08 12:04 UTC, merged